databases:
  - name: life-tracker-db
    plan: free
    databaseName: life_tracker
    user: life_tracker

services:
  - type: web
    name: life-tracker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.web:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DATABASE_URL
        fromDatabase:
          name: life-tracker-db
          property: connectionString
